### ISSUE TITLE
Direction arrow missing in sequence diagram

### ISSUE THREAD

**Issue by alordgit** [jaime-olivares/yuml-diagram#10]
After the last update of Visual Studio Code (1.26.1) the arrow heads has gone missing in our sequence diagrams.
[Robot]TaskCompleted>[PickProcess] now just show up as a straight line.

**Comment by atmclarke** [comment]
Same for me in 1.27.2

**Comment by DavidBurela** [comment]
Came here to ask the same thing. Sequence diagrams don't seem to have arrows.

**Comment by aduh95** [comment]
I don't have issues with the direction arrows, both with dark mode and light mode when generating SVG with the node API. However, if I try to add SVG elements in the same DOM using both modes, the latter one's arrows are not displayed.

```js
const yuml_diagram = require("yuml-diagram");

const sequence_diagram = `
// {type:sequence}
[:Computer]sendUnsentEmail>[:Server]
[:Computer]newEmail>[:Server]
[:Server]reponse.>[:Computer]
[:Computer]downloadEmail>[:Server]
[:Computer]deleteOldEmail>[:Server]
`;

var yuml = new yuml_diagram();
var svgLightBg = yuml.processYumlDocument(sequence_diagram, false);
var svgDarkBg = yuml.processYumlDocument(sequence_diagram, true);

console.log(`<body bgcolor="#000">${svgLightBg}${svgDarkBg}</body>`);
```

On this example, we can see that the __black arrows__ (which should be used for the "light mode") are used __for both SVGs__. I think it comes from the fact the same ID attributes are used for both theme and no sandboxing is made by the rendering engine.

https://github.com/jaime-olivares/yuml-diagram/blob/d0dc8fbbedabca2925b24d155436a37201064277/src/svg-builder.js#L108-L117

This explains why some users rapport missing arrows on the related VSCode extension as both light mode and dark mode SVG are added to the DOM; users with a dark theme won't be able to see the arrows because of the ID name clash.

To fix this issue, either we need to specify that mixing light and dark mode is not supported, either we need to somehow namespace the ID attributes to avoid the name clash.

**Comment by DavidBurela** [comment]
Thanks that does seems to be the root cause and means I have a workaround.


**Repo of bug:**
Create a .MD file in VS Code, set theme to dark.  Use this diagram (removing the . ).  Then preview the file

. ```yuml
// {type: sequence}

[Patron]order food>[Waiter]
[Waiter]serve wine.>[Patron]
[Patron]pay bill>>[Waiter]

. ```

**Workaround:**
Set VS Code theme to light

**Comment by jaime-olivares** [comment]
Please let me know if the issue has gone.
